

development:
      host: localhost
      adapter: mysql
      database: Brilliance_development
      port: 3306
      username: root




      password: root
      socket: /var/run/mysqld/mysqld.sock

test: &test
      host: localhost
      adapter: mysql
      database: Brilliance_test
      port: 3306
      username: root
      password: root
      socket: /var/run/mysqld/mysqld.sock

production:
      host: localhost
      adapter: mysql
      database: Brilliance_production
      port: 3306
      username: root
      password: root
      socket: /var/run/mysqld/mysqld.sock

cucumber:
  <<: *test
